### ISSUE TITLE
Dependencies should not be installed!

### ISSUE THREAD

**Issue by whit2333** [slaclab/slic#22]
This mighty be philosophy but this is an annoyance.

`-- Downloading...
   dst='/opt/software/builds/slic_build/XERCES-prefix/src/xerces-c-3.1.4.tar.gz'
   timeout='none'
-- Using src='http://apache.cs.utah.edu//xerces/c/3/sources/xerces-c-3.1.4.tar.gz'
-- Downloading...
   dst='/opt/software/builds/slic_build/HEPPDT-prefix/src/HepPDT-3.04.01.tar.gz'
   timeout='none'
-- Using src='http://lcgapp.cern.ch/project/simu/HepPDT/download/HepPDT-3.04.01.tar.gz'
`

This is bad form. I have these already installed! Plus it makes the code unmaintainable.

**Comment by whit2333** [comment]
Oh so it installs everything?!?!? Including LCIO? This is a **REALLY** bad idea. Just stick to building the project. Leave the dependencies as just that -- dependencies.

**Comment by JeremyMcCormick** [comment]
You're not forced to install everything.  Just supply the existing installations using LCIO_DIR, Geant4_DIR, etc. and cmake should find them.

(The cmake build on master I think is partially broken...I will merge in iss20 branch soon to fix everything.)

**Comment by whit2333** [comment]
Cmake should find them without doing anything. That is the point of using cmake! If an alternative installation other than the standard one is desired, then you can point it to its location. Downloading and installing the dependencies should be done only if give an option like `-DDownloadAndBuildDeps`.

Good defaults are important.

The reason we initially started a new fork was because the "SLIC" software-chain was using old or unmaintained libraries. It is best to just leave the dependencies alone to their maintainers and use the latest versions and fix bugs when the pop up.

**Comment by JeremyMcCormick** [comment]
The standard way to tell cmake about your pre-built dependencies is supplying directories in the form of `-DGeant4_DIR=/my/geant4/install` so that's how it works if you're using all your own copies of GDML, LCDD, Geant4, etc.  

When you rerun cmake in subsequent steps it will remember your dependency dirs in the cache so you don't have to supply them again.

We can add a flag to turn on/off the automatic dependency installation.  I think that should resolve any concerns.

**Comment by whit2333** [comment]
> The standard way to tell cmake about your pre-built dependencies is supplying directories in the form of -DGeant4_DIR=/my/geant4/install

Not true. The standard way is to use [find_package](https://cmake.org/cmake/help/v3.8/command/find_package.html).

For example
```find_package(Geant4 )```
will find `<prefix>/lib/Geant4/GeantConfig.cmake` ([here](https://gitlab.cern.ch/geant4/geant4/blob/master/cmake/Templates/Geant4Config.cmake.in) is what it looks like).
This is because geant4 follows a standard CMake build.

For other libraries that don't use cmake, you would supply a `FindXXXX.cmake`  typically  within the `cmake/modules` directory. 

From  [find_package](https://cmake.org/cmake/help/v3.8/command/find_package.html):
> The command has two modes by which it searches for packages: “Module” mode and “Config” mode. 
Module mode ...  searches for a file called Find<package>.cmake in the CMAKE_MODULE_PATH followed by the CMake installation. If the file is found, it is read and processed by CMake.
...
Config mode attempts to locate a configuration file provided by the package to be found. 

Ideally config mode would be used by every library. With module mode, one mistake I have seen multiple times is maintainers of library YYYY installing their own `FindXXXX.cmake`. Don't do this. It should only be used by the YYYY library and may hide the `XXXXConfig.cmake` supplied by the XXXX maintainer.

Cmake has changed significantly over time and there remain many projects using cmake in a very unwieldy way. <*cough*>iLCSoft<*cough*> So it is important not to emulate them.

**Comment by JeremyMcCormick** [comment]
Hi, Whitney.

You have to supply `Geant4_DIR` and other package variables on the cmake prompt when configuring your project.  CMake doesn't magically know the directories of your dependencies unless you tell it.  Some `Find` macros look in system directories but slic's 6 deps are not likely to be installed there (with the exception of perhaps some version of Xerces C++).

Then internally `find_package` is indeed used by slic's CMakeLists.txt which will either use a custom `Find` macro or a project's CMake config file if it is found.

Additionally, there are `InstallXXX.cmake` scripts for installing each of the deps, but they are only activated individually if CMake can't find a particular dep.

So what I'm doing is close to what you have described.  Did you want it to somehow work differently?  (Aside from the automatic dep install, which we can have controlled via a flag and default could potentially be set to OFF.)

I think in general that, yes, I do want the option for all deps to be installed by slic, because installing these 6 packages by yourself is not that trivial a task so I want an easy install mode (supplying all of your own deps is still possible here though).

**Comment by JeremyMcCormick** [comment]
I'm going to add an `INSTALL_DEPS` flag that will be set to `OFF` initially.  To install dependencies, you would supply `-DINSTALL_DEPS=ON` to your cmake command.  The default behavior will be a fatal error if any of the dependencies are not found.

Would this resolve this particular issue for you?

**Comment by JeremyMcCormick** [comment]
PR #27 should resolve this.
